[project]
name = "claypaths"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aider-chat>=0.81.1",
    "matplotlib>=3.10.1",
    "numpy-stl>=3.2.0",
    "pygobject>=3.52.3",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
    "shapely>=2.1.0",
]
