import numpy as np
from shapely.geometry import Polygon, LineString, Point, MultiLineString, MultiPolygon, LinearRing
from shapely.ops import polygonize, unary_union, nearest_points
import matplotlib.pyplot as plt
from typing import List, Tuple, Dict

def generate_continuous_offset_fill(polygon: Polygon, toolpath_width: float):
    """
    Generates a continuous toolpath for a polygon using iterative offsetting
    and breakpoint connections, based on the described algorithm.

    Args:
        polygon: The Shapely Polygon to fill (must have exterior, may have interiors).
        toolpath_width: The distance between toolpaths (offset distance).

    Returns:
        A single Shapely LineString representing the continuous toolpath,
        or None if filling is not possible.
    """
    if not isinstance(polygon, Polygon) or polygon.is_empty:
        print("Warning: Invalid or empty polygon provided for continuous offset fill.")
        return None

    all_contours = []
    current_polygon = polygon

    # 1. Contour Offsetting (Iterative Inward Offsetting)
    level = 0
    while True:
        # Perform inward offset
        # Note: Negative offset for inward direction
        offset_polygon = current_polygon.buffer(-toolpath_width, join_style=2) # MITRE join

        # Clean up potential small artifacts or invalid geometries
        if not offset_polygon.is_valid:
            offset_polygon = offset_polygon.buffer(0)

        if offset_polygon.is_empty or not isinstance(offset_polygon, (Polygon, MultiPolygon)):
            break # Stop if offset results in nothing or non-polygonal shapes

        contours_at_level = []
        if isinstance(offset_polygon, Polygon):
            # Add exterior
            if not offset_polygon.exterior.is_empty:
                 contours_at_level.append(offset_polygon.exterior)
            # Add interiors (holes generated by offsetting)
            # These become "outer" contours for the *next* iteration's perspective
            # but are stored as LineStrings here.
            for interior in offset_polygon.interiors:
                 if not interior.is_empty:
                     contours_at_level.append(interior)

        elif isinstance(offset_polygon, MultiPolygon):
             for poly in offset_polygon.geoms:
                 if isinstance(poly, Polygon):
                     if not poly.exterior.is_empty:
                         contours_at_level.append(poly.exterior)
                     for interior in poly.interiors:
                         if not interior.is_empty:
                             contours_at_level.append(interior)

        if not contours_at_level:
            break # No valid contours generated at this level

        # Store contours with their level (higher level means further inside)
        all_contours.extend([(level, contour) for contour in contours_at_level])

        # Prepare for next iteration: the offset polygon becomes the new boundary
        current_polygon = offset_polygon
        level += 1

    if not all_contours:
        print("Warning: No offset contours generated.")
        return None

    # Add the original polygon's boundary (level -1, conceptually)
    # We need both exterior and interiors as starting contours
    initial_contours = [polygon.exterior] + list(polygon.interiors)
    all_contours = [(-1, initial) for initial in initial_contours] + all_contours

    # Re-level contours (Algorithm 1 is implicitly handled by iterative offsetting)
    # Sort contours primarily by level (descending, so innermost is first)
    # Secondary sort could be added if needed (e.g., by area if multiple contours at same level)
    # For now, the iterative generation order should suffice if we process level by level.
    # Let's reverse the list so outermost is first (level -1, 0, 1, ...)
    all_contours.sort(key=lambda item: item[0]) # Sort by level ascending (-1, 0, 1, ...)

    print(f"Generated {len(all_contours)} total contours across {level+1} effective levels (including original).")

    if not all_contours:
        return None # No contours to process

    # Group contours by level
    contours_by_level: Dict[int, List[LineString]] = {}
    for lvl, contour in all_contours:
        # Ensure contours are LineStrings for consistency
        if isinstance(contour, LinearRing):
             contour_line = LineString(contour.coords)
        elif isinstance(contour, LineString):
             contour_line = contour
        else:
             print(f"Warning: Skipping unexpected geometry type in contours: {type(contour)}")
             continue

        if lvl not in contours_by_level:
            contours_by_level[lvl] = []
        contours_by_level[lvl].append(contour_line)

    # Handle case with only one level (no offsetting possible or needed)
    if len(contours_by_level) <= 1:
         print("Only one contour level found, returning the original contour(s).")
         # Return the original polygon boundary(ies) as a MultiLineString or single LineString
         original_level = min(contours_by_level.keys())
         if len(contours_by_level[original_level]) == 1:
             return contours_by_level[original_level][0]
         else:
             return MultiLineString(contours_by_level[original_level])


    # 2. Finding Breakpoints
    print("Step 2: Finding breakpoints between adjacent contours...")
    breakpoints = _find_breakpoints(contours_by_level, toolpath_width)

    if not breakpoints:
        print("Warning: Could not find any breakpoints. Returning raw contours.")
        # Fallback: return the contours as separate lines
        all_lines = [line for lvl_lines in contours_by_level.values() for line in lvl_lines]
        if len(all_lines) == 1:
            return all_lines[0]
        elif len(all_lines) > 1:
            return MultiLineString(all_lines)
        else:
            return None

    # 3. Generating Continuous Path (combines forming sub-paths and connecting)
    print("Step 3: Building continuous path...")
    continuous_path = _build_continuous_path(contours_by_level, breakpoints)

    if continuous_path:
        print("Successfully generated continuous path.")
        # Optional visualization call:
        # visualize_contours_and_path(polygon, continuous_path, "Continuous Offset Fill")
    else:
        print("Failed to generate continuous path.")
        # Fallback? Return raw contours?
        all_lines = [line for lvl_lines in contours_by_level.values() for line in lvl_lines]
        if len(all_lines) == 1: return all_lines[0]
        elif len(all_lines) > 1: return MultiLineString(all_lines)
        else: return None


    return continuous_path


def visualize_contours_and_path(polygon, path, title="Continuous Offset Fill"):
    """Helper function to visualize the polygon and the generated path."""
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_aspect('equal', adjustable='box')

    # Plot polygon
    if polygon:
        x, y = polygon.exterior.xy
        ax.plot(x, y, color='black', linewidth=1, solid_capstyle='round', label='Original Polygon')
        for interior in polygon.interiors:
            xi, yi = interior.xy
            ax.plot(xi, yi, color='grey', linewidth=1, solid_capstyle='round')

    # Plot path
    if path:
        if isinstance(path, LineString):
            xp, yp = path.xy
            ax.plot(xp, yp, color='blue', linewidth=1.5, solid_capstyle='round', label='Toolpath')
        elif isinstance(path, MultiLineString):
             for line in path.geoms:
                 xp, yp = line.xy
                 ax.plot(xp, yp, color='blue', linewidth=1.5, solid_capstyle='round')


    ax.set_title(title)
    ax.legend()
    plt.show()

# --- Helper Functions ---

def _get_point_on_line_closest_to_point(target_point: Point, line: LineString) -> Point:
    """Finds the point on a LineString closest to a target Point."""
    if not isinstance(target_point, Point) or not isinstance(line, LineString):
        raise ValueError("Inputs must be Shapely Point and LineString")
    if line.is_empty:
        return None
    # Project the point onto the line and interpolate to get the point
    distance = line.project(target_point)
    closest_point = line.interpolate(distance)
    return closest_point

def _find_closest_points_between_lines(line1: LineString, line2: LineString) -> Tuple[Point, Point]:
    """
    Finds the pair of points (one on each line) that are closest to each other.
    Uses shapely.ops.nearest_points.
    """
    if not isinstance(line1, LineString) or not isinstance(line2, LineString) or line1.is_empty or line2.is_empty:
        # Return None or raise error if lines are invalid
        return None, None
    try:
        p1, p2 = nearest_points(line1, line2)
        return p1, p2
    except Exception as e:
        print(f"Warning: Could not find nearest points between lines: {e}")
        # Fallback or error handling: maybe return centroids or None
        return None, None


def _traverse_contour_from_point(contour: LineString, start_point: Point) -> List[Tuple[float, float]]:
    """
    Reorders the coordinates of a closed contour (LineString) to start
    near the specified start_point and traverse the loop.

    Args:
        contour: The closed LineString (should have matching start/end points).
        start_point: The Point near which the traversal should begin.

    Returns:
        A list of coordinate tuples representing the traversed path.
        Returns None if contour is invalid.
    """
    if not contour or contour.is_empty or len(contour.coords) < 3:
        return None # Cannot traverse an empty or too short line

    coords = list(contour.coords)
    if coords[0] != coords[-1]:
         # If not explicitly closed, close it for traversal logic
         coords.append(coords[0])

    # Find the index of the vertex closest to the start_point
    min_dist = float('inf')
    start_index = 0
    for i, pt_coords in enumerate(coords[:-1]): # Exclude the closing point for index finding
        dist = start_point.distance(Point(pt_coords))
        if dist < min_dist:
            min_dist = dist
            start_index = i

    # Reorder coordinates: start from start_index, wrap around, end at start_index
    # Exclude the repeated start point at the very end of the list
    reordered_coords = coords[start_index:-1] + coords[:start_index+1]

    # Ensure the start point is *exactly* the first point if needed,
    # or handle potential floating point issues if start_point isn't exactly a vertex.
    # For now, starting at the *closest vertex* is sufficient.

    return reordered_coords


# --- Core Algorithm Implementation ---

def _find_breakpoints(contours_by_level: Dict[int, List[LineString]], toolpath_width: float) -> List[Tuple[int, LineString, Point, LineString, Point]]:
    """
    Finds breakpoints (closest points) between contours in adjacent levels.

    Args:
        contours_by_level: Dict mapping level index to list of LineString contours.
        toolpath_width: The target distance between paths (used for validation/info).

    Returns:
        List of tuples: (level, outer_contour, breakpoint_outer, inner_contour, breakpoint_inner)
        sorted by level.
    """
    breakpoints = []
    levels = sorted(contours_by_level.keys())

    if len(levels) < 2:
        print("Warning: Not enough contour levels to find breakpoints.")
        return []

    # Iterate through adjacent levels (e.g., level 0 and 1, level 1 and 2, ...)
    for i in range(len(levels) - 1):
        level_outer_idx = levels[i]
        level_inner_idx = levels[i+1]
        contours_outer = contours_by_level[level_outer_idx]
        contours_inner = contours_by_level[level_inner_idx]

        # Simple matching: Assume each outer contour corresponds to one inner contour.
        # More complex logic (spatial checks) needed for multi-part polygons or complex offsets.
        # For now, iterate through outer contours and find the *first* valid inner contour match.
        # This might fail if an outer contour generates multiple separate inner contours.
        matched_inner_contours = set()

        for outer_contour in contours_outer:
            best_match_inner = None
            min_dist = float('inf')
            closest_p_outer = None
            closest_p_inner = None

            # Find the best inner contour match for this outer contour
            # Basic approach: find the inner contour whose nearest point is closest
            potential_matches = []
            for inner_contour in contours_inner:
                 # Basic check: skip if already matched (simplistic)
                 # if inner_contour in matched_inner_contours:
                 #    continue

                 p_outer, p_inner = _find_closest_points_between_lines(outer_contour, inner_contour)
                 if p_outer is not None and p_inner is not None:
                     dist = p_outer.distance(p_inner)
                     potential_matches.append((dist, p_outer, p_inner, inner_contour))

            if not potential_matches:
                 print(f"Warning: No inner contour found for outer contour at level {level_outer_idx}")
                 continue

            # Select the inner contour with the minimum distance connection
            potential_matches.sort(key=lambda x: x[0])
            min_dist, closest_p_outer, closest_p_inner, best_match_inner = potential_matches[0]

            # Optional: Check if distance is reasonable compared to toolpath_width
            # if not np.isclose(min_dist, toolpath_width, atol=toolpath_width * 0.5):
            #     print(f"Warning: Breakpoint distance {min_dist:.3f} differs significantly from toolpath width {toolpath_width} between levels {level_outer_idx} and {level_inner_idx}")

            if best_match_inner:
                breakpoints.append((
                    level_outer_idx,
                    outer_contour,
                    closest_p_outer,
                    best_match_inner,
                    closest_p_inner
                ))
                # Mark inner contour as matched (simplistic)
                # Mark inner contour as matched (simplistic)
                # matched_inner_contours.add(best_match_inner) # Be careful with object identity vs value

    print(f"Found {len(breakpoints)} breakpoints between contour levels.")
    return breakpoints

def _form_subpaths(contours_with_breakpoints):
    """Forms sub-paths by breaking contours at breakpoints."""
    # This logic is integrated into _build_continuous_path now.
    pass

def _build_continuous_path(contours_by_level: Dict[int, List[LineString]],
                           breakpoints: List[Tuple[int, LineString, Point, LineString, Point]]) -> LineString:
    """
    Connects contours using breakpoints to form a single continuous path.

    Args:
        contours_by_level: Dict mapping level index to list of LineString contours.
        breakpoints: List of breakpoint tuples generated by _find_breakpoints.

    Returns:
        A single LineString representing the continuous toolpath, or None if failed.
    """
    if not breakpoints:
        print("Warning: No breakpoints provided, cannot build continuous path.")
        # Handle case with only one contour level (e.g., return the contour itself?)
        levels = sorted(contours_by_level.keys())
        if len(levels) == 1 and contours_by_level[levels[0]]:
            # Return the first contour of the only level if no breakpoints needed
            return contours_by_level[levels[0]][0]
        return None

    final_path_coords = []
    processed_contours = set() # Keep track of contours already traversed

    # Sort breakpoints by level to process connections sequentially
    breakpoints.sort(key=lambda x: x[0])

    # Start with the first breakpoint connection
    level, outer_contour, p_outer, inner_contour, p_inner = breakpoints[0]

    # --- Handle the very first contour (outermost) ---
    # Traverse the first outer contour starting from its breakpoint
    traversal_coords = _traverse_contour_from_point(outer_contour, p_outer)
    if traversal_coords:
        final_path_coords.extend(traversal_coords)
        processed_contours.add(outer_contour.wkt) # Use WKT for hashable representation
    else:
        print(f"Error: Failed to traverse initial outer contour at level {level}")
        return None

    # Add the first connection segment (outer breakpoint to inner breakpoint)
    # The traversal already ends at p_outer (or closest vertex), directly add p_inner
    final_path_coords.append((p_inner.x, p_inner.y))

    # --- Iterate through the remaining connections ---
    for i in range(len(breakpoints)):
        level, current_contour, p_current_break, next_contour, p_next_break = breakpoints[i]

        # Traverse the current_contour (which was the 'inner' contour of the previous step)
        # starting from its breakpoint p_current_break
        if current_contour.wkt not in processed_contours:
            traversal_coords = _traverse_contour_from_point(current_contour, p_current_break)
            if traversal_coords:
                # Ensure the traversal starts near p_current_break and ends there.
                # The list should contain the full loop.
                final_path_coords.extend(traversal_coords[1:]) # Skip first point (already added)
                processed_contours.add(current_contour.wkt)
            else:
                print(f"Error: Failed to traverse contour at level {level}")
                # Decide how to handle failure: stop or try to continue?
                continue # Skip this contour for now

        # Add the connection segment to the *next* contour's breakpoint
        # Check if there is a next breakpoint involving this 'next_contour'
        if i + 1 < len(breakpoints):
             # Find the breakpoint where 'next_contour' acts as the outer part
             next_break_info = None
             for bp in breakpoints[i+1:]:
                 if bp[1] == next_contour: # If next_contour is the outer contour in a future breakpoint
                     next_break_info = bp
                     break

             if next_break_info:
                 # Connect from current position (end of traversal = p_current_break)
                 # to the breakpoint on the next_contour (p_next_break)
                 final_path_coords.append((p_next_break.x, p_next_break.y))
             else:
                 # This 'next_contour' is the innermost in this chain, traverse it last
                 pass # Will be handled after loop
        else:
             # This is the last breakpoint, 'next_contour' is the innermost
             # Connect to its breakpoint p_next_break
             final_path_coords.append((p_next_break.x, p_next_break.y))


    # --- Handle the very last contour (innermost) ---
    # The last breakpoint processed was (level, current_contour, p_current, next_contour, p_next)
    # We are now at p_next on next_contour (the innermost one). Traverse it.
    last_contour = breakpoints[-1][3] # The 'inner_contour' of the last breakpoint
    last_breakpoint = breakpoints[-1][4] # The 'breakpoint_inner' of the last breakpoint

    if last_contour.wkt not in processed_contours:
        traversal_coords = _traverse_contour_from_point(last_contour, last_breakpoint)
        if traversal_coords:
            # Add traversal, skipping the first point (already at last_breakpoint)
            final_path_coords.extend(traversal_coords[1:])
            processed_contours.add(last_contour.wkt)
        else:
            print(f"Error: Failed to traverse final inner contour at level {breakpoints[-1][0]+1}")
            # Path might be incomplete

    if not final_path_coords:
        print("Error: No path coordinates generated.")
        return None

    # Create the final LineString
    try:
        final_path = LineString(final_path_coords)
        if not final_path.is_valid:
             print("Warning: Generated continuous path is not valid. Attempting buffer(0).")
             final_path = final_path.buffer(0) # Clean up potential self-intersections near connections
             if not isinstance(final_path, LineString): # Buffer(0) might return Polygon/MultiLineString
                 print("Error: Path cleanup resulted in non-LineString geometry.")
                 # Fallback: return original coords? Or handle MultiLineString?
                 # For now, return None if cleanup fails badly.
                 return None
        return final_path
    except Exception as e:
        print(f"Error creating final LineString: {e}")
        return None
