import os
from datetime import datetime
from src.config import get_config

class GCodeGenerator:
    """
    Generates GCode from optimized toolpaths for clay paste extrusion.
    Only includes movement commands with consistent speed.
    """
    
    def __init__(self, flavor=None):
        """
        Initialize the GCode generator.
        
        Args:
            flavor (str, optional): GCode flavor, either "klipper" or "marlin".
                                   If None, uses the value from config.
        """
        config = get_config()
        
        self.flavor = flavor.lower() if flavor else config['gcode_flavor'].lower()
        self.movement_speed = config['print_speed']  # mm/s - consistent speed for all movements
        self.acceleration = config['acceleration']   # mm/s²
        self.layer_height = config.get('layer_height', 1.0)  # mm
        
    def generate_header(self):
        """Generate the GCode header with initialization commands."""
        header = []
        header.append("; GCode generated by claypaths for clay paste extrusion")
        header.append(f"; Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        header.append(f"; Flavor: {self.flavor}")
        header.append("")
        
        # Basic setup commands for any printer
        header.append("G90 ; Use absolute coordinates")
        header.append(f"G1 F{self.movement_speed * 60} ; Set consistent movement speed")
        
        if self.flavor == "klipper":
            header.append(f"SET_VELOCITY_LIMIT ACCEL={self.acceleration} ; Set acceleration")
        else:  # marlin
            header.append(f"M204 P{self.acceleration} ; Set acceleration")
        
        header.append("G28 ; Home all axes")
        header.append("")
            
        return "\n".join(header)
    
    def generate_footer(self):
        """Generate the GCode footer with finalization commands."""
        footer = []
        footer.append("")
        footer.append("; End GCode")
        footer.append(f"G1 Z30 F{self.movement_speed * 60} ; Lift nozzle")
        footer.append("M84 ; Disable motors")
            
        return "\n".join(footer)
    
    def generate_layer_transition(self, z_height):
        """
        Generate commands for transitioning to a new layer.
        
        Args:
            z_height (float): The Z height of the new layer
            
        Returns:
            str: GCode commands for layer transition
        """
        commands = []
        commands.append(f"; Layer at Z={z_height:.3f}")
        commands.append(f"G1 Z{z_height:.3f}")
        return "\n".join(commands)
    
    def generate_path_commands(self, path, z_height, is_first_point=False):
        """
        Generate GCode commands for a path at a specific Z height.
        
        Args:
            path (list): List of (x, y) coordinates or Shapely Points
            z_height (float): Z height for this path
            is_first_point (bool): Whether this is the first point in the print
            
        Returns:
            str: GCode commands for the path
        """
        if not path:
            return "; Empty path"
        
        commands = []
        
        # Handle different path formats
        if all(hasattr(p, 'x') and hasattr(p, 'y') for p in path):  # It's a list of Shapely Points
            # Check if points have z-coordinate and use it if available
            if hasattr(path[0], 'z') and path[0].z is not None:
                # Use the z-coordinate from each point
                points = [(p.x, p.y, p.z) for p in path]
            else:
                # Use the provided z_height for all points
                points = [(p.x, p.y, z_height) for p in path]
        else:  # It's a list of coordinate tuples
            # Check if tuples include z-coordinate
            if len(path[0]) >= 3:
                points = path  # Already has z-coordinate
            else:
                # Add z_height to each point
                points = [(p[0], p[1], z_height) for p in path]
            
        # First point - move to position
        first_point = points[0]
        x, y, point_z = first_point
        if is_first_point:
            commands.append(f"; Starting first layer path")
            commands.append(f"G1 X{x:.3f} Y{y:.3f} Z{point_z:.3f}")
        else:
            commands.append(f"; Starting new path segment")
            commands.append(f"G1 X{x:.3f} Y{y:.3f} Z{point_z:.3f}")
        
        # Remaining points - all moves at consistent speed
        for point in points[1:]:
            x, y, point_z = point
            commands.append(f"G1 X{x:.3f} Y{y:.3f} Z{point_z:.3f}")
            
        return "\n".join(commands)
    
    def generate_gcode(self, layers, optimized_paths, min_z):
        """
        Generate complete GCode for all layers.
        
        Args:
            layers (list): List of layer contours
            optimized_paths (list): List of optimized paths for each layer
            min_z (float): Minimum Z height of the model
            
        Returns:
            str: Complete GCode
        """
        if not layers or not optimized_paths:
            return "; No valid layers or paths"
        
        gcode = []
        gcode.append(self.generate_header())
        
        # Process each layer
        for layer_idx, layer_paths in enumerate(optimized_paths):
            if not layer_paths:
                gcode.append(f"; Skipping layer {layer_idx} - no valid path")
                continue
            
            # Calculate Z height for this layer (used as fallback)
            z_height = min_z + (layer_idx * self.layer_height)
            
            # Add layer transition
            gcode.append(self.generate_layer_transition(z_height))
            
            # Process each path in the layer
            for path_idx, path in enumerate(layer_paths):
                if not path:
                    continue
                
                # Add path commands
                is_first_point = (layer_idx == 0 and path_idx == 0)
                gcode.append(self.generate_path_commands(path, z_height, is_first_point))
        
        gcode.append(self.generate_footer())
        return "\n".join(gcode)
    
    def save_gcode(self, gcode, output_dir="gcode"):
        """
        Save GCode to a file with timestamp in the filename.
        
        Args:
            gcode (str): The GCode to save
            output_dir (str): Directory to save the file
            
        Returns:
            str: Path to the saved file
        """
        # Create output directory if it doesn't exist
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"claypaths_{timestamp}.gcode"
        filepath = os.path.join(output_dir, filename)
        
        # Write GCode to file
        with open(filepath, 'w') as f:
            f.write(gcode)
            
        return filepath
