import os
from datetime import datetime
from src.config import get_config

class GCodeGenerator:
    """
    Generates GCode from optimized toolpaths for clay paste extrusion.
    Only includes movement commands with consistent speed.
    """
    
    def __init__(self, flavor=None):
        """
        Initialize the GCode generator.
        
        Args:
            flavor (str, optional): GCode flavor, either "klipper" or "marlin".
                                   If None, uses the value from config.
        """
        config = get_config()
        
        self.flavor = flavor.lower() if flavor else config['gcode_flavor'].lower()
        self.movement_speed = config['print_speed']  # mm/s - consistent speed for all movements
        self.travel_speed = config.get('travel_speed', self.movement_speed * 1.5)  # mm/s - faster for non-extrusion moves
        self.acceleration = config['acceleration']   # mm/s²
        self.layer_height = config.get('layer_height', 1.0)  # mm
        
        # Extrusion parameters
        self.extrusion_rate = config.get('extrusion_rate', 1.0)  # Extrusion multiplier
        self.extrusion_enabled = config.get('extrusion_enabled', True)  # Global switch for extrusion
        self.retraction_distance = config.get('retraction_distance', 2.0)  # mm
        self.retraction_speed = config.get('retraction_speed', 40)  # mm/s
        
    def generate_header(self):
        """Generate the GCode header with initialization commands."""
        header = []
        header.append("; GCode generated by claypaths for clay paste extrusion")
        header.append(f"; Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        header.append(f"; Flavor: {self.flavor}")
        header.append(f"; Extrusion rate: {self.extrusion_rate}")
        header.append("")
        
        # Basic setup commands for any printer
        header.append("G90 ; Use absolute coordinates")
        header.append("G21 ; Set units to millimeters")
        header.append(f"G1 F{self.movement_speed * 60} ; Set initial movement speed")
        
        if self.flavor == "klipper":
            header.append(f"SET_VELOCITY_LIMIT ACCEL={self.acceleration} ; Set acceleration")
            header.append("SET_PRESSURE_ADVANCE ADVANCE=0.02 ; Set pressure advance for clay")
        else:  # marlin
            header.append(f"M204 P{self.acceleration} ; Set acceleration")
            header.append("M92 E100 ; Set extruder steps per unit for clay")
        
        header.append("G28 ; Home all axes")
        header.append("G1 Z10 F300 ; Lift nozzle to prevent scratching")
        header.append("G92 E0 ; Reset extruder position")
        header.append("")
            
        return "\n".join(header)
    
    def generate_footer(self):
        """Generate the GCode footer with finalization commands."""
        footer = []
        footer.append("")
        footer.append("; End GCode")
        
        # Retract to stop oozing
        if self.extrusion_enabled:
            footer.append(f"G1 E-{self.retraction_distance} F{self.retraction_speed * 60} ; Retract to prevent oozing")
        
        footer.append(f"G1 Z30 F{self.travel_speed * 60} ; Lift nozzle")
        footer.append("M104 S0 ; Turn off extruder")
        footer.append("M84 ; Disable motors")
            
        return "\n".join(footer)
    
    def generate_layer_transition(self, z_height):
        """
        Generate commands for transitioning to a new layer.
        
        Args:
            z_height (float): The Z height of the new layer
            
        Returns:
            str: GCode commands for layer transition
        """
        commands = []
        commands.append(f"; Layer at Z={z_height:.3f}")
        
        # Retract before layer change if extrusion is enabled
        if self.extrusion_enabled:
            commands.append(f"G1 E-{self.retraction_distance} F{self.retraction_speed * 60} ; Retract before layer change")
        
        # Move to new layer height with travel speed
        commands.append(f"G1 Z{z_height:.3f} F{self.travel_speed * 60}")
        
        # Reset speed to movement speed for printing
        commands.append(f"G1 F{self.movement_speed * 60} ; Reset to print speed")
        
        # Prime after layer change if extrusion is enabled
        if self.extrusion_enabled:
            commands.append(f"G1 E{self.retraction_distance} F{self.retraction_speed * 60} ; Prime after layer change")
        
        return "\n".join(commands)
    
    def generate_path_commands(self, path, z_height, is_first_point=False, is_connecting_path=False):
        """
        Generate GCode commands for a path at a specific Z height.
        
        Args:
            path (list): List of (x, y) coordinates or Shapely Points
            z_height (float): Z height for this path
            is_first_point (bool): Whether this is the first point in the print
            is_connecting_path (bool): Whether this is a connecting path (no extrusion)
            
        Returns:
            str: GCode commands for the path
        """
        if not path:
            return "; Empty path"
        
        commands = []
        
        # Handle different path formats
        if all(hasattr(p, 'x') and hasattr(p, 'y') for p in path):  # It's a list of Shapely Points
            # Safely check if points have z-coordinate and use it if available
            # Use a try/except block to handle the DimensionError that Shapely raises
            try:
                # Try to access z coordinate of first point to check if it exists
                test_z = path[0].z
                # If we get here, z exists and we can use it for all points
                points = [(p.x, p.y, p.z) for p in path]
            except (AttributeError, Exception):
                # Use the provided z_height for all points if z coordinate doesn't exist
                points = [(p.x, p.y, z_height) for p in path]
        else:  # It's a list of coordinate tuples
            # Check if tuples include z-coordinate
            if len(path[0]) >= 3:
                points = path  # Already has z-coordinate
            else:
                # Add z_height to each point
                points = [(p[0], p[1], z_height) for p in path]
        
        # Determine if we should extrude during this path
        should_extrude = self.extrusion_enabled and not is_connecting_path
        
        # First point - move to position (travel move, no extrusion)
        first_point = points[0]
        x, y, point_z = first_point
        
        if is_first_point:
            commands.append(f"; Starting first layer path")
            commands.append(f"G1 X{x:.3f} Y{y:.3f} Z{point_z:.3f} F{self.travel_speed * 60} ; Travel to start")
        else:
            commands.append(f"; Starting new path segment")
            # If this is a connecting path, use travel speed
            speed = self.travel_speed if is_connecting_path else self.movement_speed
            commands.append(f"G1 X{x:.3f} Y{y:.3f} Z{point_z:.3f} F{speed * 60}")
        
        # If we should extrude and this isn't the first point, prime the extruder
        if should_extrude and not is_first_point:
            commands.append(f"G1 E{self.retraction_distance} F{self.retraction_speed * 60} ; Prime before path")
            commands.append(f"G1 F{self.movement_speed * 60} ; Set to print speed")
            commands.append(f"G92 E0 ; Reset extruder position for path")
        
        # Remaining points - with extrusion if enabled
        e_position = 0
        for i, point in enumerate(points[1:]):
            x, y, point_z = point
            
            if should_extrude:
                # Calculate extrusion amount based on distance moved
                prev_x, prev_y, _ = points[i]
                distance = ((x - prev_x)**2 + (y - prev_y)**2)**0.5
                e_position += distance * self.extrusion_rate
                commands.append(f"G1 X{x:.3f} Y{y:.3f} Z{point_z:.3f} E{e_position:.4f}")
            else:
                # No extrusion for connecting paths
                commands.append(f"G1 X{x:.3f} Y{y:.3f} Z{point_z:.3f}")
        
        # If we extruded during this path, retract at the end
        if should_extrude:
            commands.append(f"G1 E{e_position - self.retraction_distance} F{self.retraction_speed * 60} ; Retract after path")
            
        return "\n".join(commands)
    
    def generate_gcode(self, layers, optimized_paths, min_z, path_metadata=None):
        """
        Generate complete GCode for all layers.
        
        Args:
            layers (list): List of layer contours
            optimized_paths (list): List of optimized paths for each layer
            min_z (float): Minimum Z height of the model
            path_metadata (dict, optional): Metadata for the path including breakpoint connections
            
        Returns:
            str: Complete GCode
        """
        # Store path metadata for use in processing
        path_with_metadata = path_metadata
        if not layers or not optimized_paths:
            return "; No valid layers or paths"
        
        gcode = []
        gcode.append(self.generate_header())
        
        # For global path processing (when we have a single continuous path across all layers)
        if len(optimized_paths) == 1 and len(optimized_paths[0]) == 1:
            # We have a single global path that spans all layers
            global_path = optimized_paths[0][0]
            
            # Create a mapping of point indices to layer indices
            point_to_layer_map = {}
            current_z = None
            current_layer = -1
            
            # Map each point to its corresponding layer based on z-height
            for i, point in enumerate(global_path):
                try:
                    point_z = point.z
                    # If this is a new z-height, it's a new layer
                    if point_z != current_z:
                        current_z = point_z
                        current_layer += 1
                    point_to_layer_map[i] = current_layer
                except (AttributeError, Exception):
                    # If point has no z-coordinate, estimate layer based on index
                    estimated_layer = min(len(layers)-1, int(i / (len(global_path) / len(layers))))
                    point_to_layer_map[i] = estimated_layer
            
            # Process the global path with layer transitions
            current_layer = -1
            prev_z = None
            e_position = 0
            
            # Reset extruder at start
            gcode.append("G92 E0 ; Reset extruder position")
            
            for i, point in enumerate(global_path):
                # Check if we're entering a new layer
                point_layer = point_to_layer_map[i]
                
                # Get the z-height for this point
                try:
                    point_z = point.z
                except (AttributeError, Exception):
                    point_z = min_z + (point_layer * self.layer_height)
                
                # Detect layer transitions
                if point_layer != current_layer:
                    current_layer = point_layer
                    # Add layer transition
                    gcode.append(self.generate_layer_transition(point_z))
                    gcode.append(f"; Starting layer {current_layer}")
                    # Reset extruder position after layer change
                    gcode.append("G92 E0 ; Reset extruder position for new layer")
                    e_position = 0
                    prev_z = point_z
                
                # Detect if this is a connecting move (significant z change without layer change)
                is_connecting_move = prev_z is not None and abs(point_z - prev_z) > 0.1 * self.layer_height
                
                # For the first point, we need a complete move command (travel move)
                if i == 0:
                    gcode.append(f"G1 X{point.x:.3f} Y{point.y:.3f} Z{point_z:.3f} F{self.travel_speed * 60} ; Initial position")
                    gcode.append(f"G1 F{self.movement_speed * 60} ; Set to print speed")
                else:
                    # For subsequent points, determine if this is a printing move or travel move
                    prev_point = global_path[i-1]
                    
                    # Calculate distance moved
                    try:
                        prev_x, prev_y = prev_point.x, prev_point.y
                    except (AttributeError, Exception):
                        prev_x, prev_y = prev_point[0], prev_point[1]
                    
                    try:
                        curr_x, curr_y = point.x, point.y
                    except (AttributeError, Exception):
                        curr_x, curr_y = point[0], point[1]
                    
                    distance = ((curr_x - prev_x)**2 + (curr_y - prev_y)**2)**0.5
                    
                    # Only consider breakpoint connections as travel moves
                    # Check if this point is part of a breakpoint connection
                    is_breakpoint_connection = False
                    
                    # Get breakpoint connections from the metadata passed separately
                    breakpoint_connections = {}
                    if 'path_with_metadata' in locals() and isinstance(path_with_metadata, dict):
                        breakpoint_connections = path_with_metadata.get('breakpoint_connections', {})
                    
                    # Check if this point index is in any breakpoint connection
                    for bp_idx, segment_indices in breakpoint_connections.items():
                        if i in segment_indices:
                            is_breakpoint_connection = True
                            break
                    
                    if is_breakpoint_connection:
                        # Retract before travel if extrusion is enabled
                        if self.extrusion_enabled and e_position > 0:
                            gcode.append(f"G1 E{e_position - self.retraction_distance} F{self.retraction_speed * 60} ; Retract before breakpoint travel")
                        
                        # Travel move
                        gcode.append(f"G1 X{curr_x:.3f} Y{curr_y:.3f} Z{point_z:.3f} F{self.travel_speed * 60} ; Breakpoint travel move")
                        
                        # Prime after travel if extrusion is enabled
                        if self.extrusion_enabled:
                            gcode.append(f"G1 E{e_position} F{self.retraction_speed * 60} ; Prime after breakpoint travel")
                            gcode.append(f"G1 F{self.movement_speed * 60} ; Reset to print speed")
                    else:
                        # Regular extrusion move (not a breakpoint connection)
                        if self.extrusion_enabled:
                            e_position += distance * self.extrusion_rate
                            gcode.append(f"G1 X{curr_x:.3f} Y{curr_y:.3f} Z{point_z:.3f} E{e_position:.4f}")
                        else:
                            gcode.append(f"G1 X{curr_x:.3f} Y{curr_y:.3f} Z{point_z:.3f}")
                
                prev_z = point_z
        else:
            # Process each layer separately (original behavior)
            for layer_idx, layer_paths in enumerate(optimized_paths):
                if not layer_paths:
                    gcode.append(f"; Skipping layer {layer_idx} - no valid path")
                    continue
                
                # Calculate Z height for this layer (used as fallback)
                z_height = min_z + (layer_idx * self.layer_height)
                
                # Add layer transition
                gcode.append(self.generate_layer_transition(z_height))
                gcode.append("G92 E0 ; Reset extruder position for new layer")
                
                # Process each path in the layer
                for path_idx, path in enumerate(layer_paths):
                    if not path:
                        continue
                    
                    # Determine if this is a connecting path
                    # For simplicity, we'll consider very short paths (less than 3 points) as connecting paths
                    is_connecting_path = len(path) < 3
                    
                    # Add path commands
                    is_first_point = (layer_idx == 0 and path_idx == 0)
                    gcode.append(self.generate_path_commands(path, z_height, is_first_point, is_connecting_path))
        
        gcode.append(self.generate_footer())
        return "\n".join(gcode)
    
    def save_gcode(self, gcode, output_dir="gcode"):
        """
        Save GCode to a file with timestamp in the filename.
        
        Args:
            gcode (str): The GCode to save
            output_dir (str): Directory to save the file
            
        Returns:
            str: Path to the saved file
        """
        # Create output directory if it doesn't exist
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"claypaths_{timestamp}.gcode"
        filepath = os.path.join(output_dir, filename)
        
        # Write GCode to file
        with open(filepath, 'w') as f:
            f.write(gcode)
            
        return filepath
